#!/bin/sh
#
# @name tetli, fixed pitch (gz)
#
# @type Custom
#
# Generated vehicle constants: configs/vehicle/tetli.yaml in the tetli repo.
#

. ${R}etc/init.d/rc.tetli_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=tetli_arena}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=tetli_fp}

param set-default SIM_GZ_EN 1
param set-default TL_VEHICLE 0
param set-default TL_KATT 10

# Six reversible motors: 0..1000 with 500 = zero speed, which is also the disarmed value.
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_DIS1 500
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_DIS2 500
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_DIS3 500
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_DIS4 500
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_DIS5 500
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_MIN6 0
param set-default SIM_GZ_EC_MAX6 1000
param set-default SIM_GZ_EC_DIS6 500
