#!/bin/sh
#
# @name tetli, variable pitch (gz)
#
# @type Custom
#
# Generated vehicle constants: configs/vehicle/tetli.yaml in the tetli repo.
#

. ${R}etc/init.d/rc.tetli_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=tetli_arena}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=tetli_vp}

param set-default SIM_GZ_EN 1
param set-default TL_VEHICLE 2
param set-default TL_KATT 20

# Six blade-pitch servos: gz_bridge servo_i carries the commanded pitch in rad.
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206
param set-default SIM_GZ_SV_MINA1 -30
param set-default SIM_GZ_SV_MAXA1 30
param set-default SIM_GZ_SV_MINA2 -30
param set-default SIM_GZ_SV_MAXA2 30
param set-default SIM_GZ_SV_MINA3 -30
param set-default SIM_GZ_SV_MAXA3 30
param set-default SIM_GZ_SV_MINA4 -30
param set-default SIM_GZ_SV_MAXA4 30
param set-default SIM_GZ_SV_MINA5 -30
param set-default SIM_GZ_SV_MAXA5 30
param set-default SIM_GZ_SV_MINA6 -30
param set-default SIM_GZ_SV_MAXA6 30

# Six constant-speed motors: 0..1000 = 0..nominal rpm, stopped when disarmed.
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_DIS1 0
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_DIS2 0
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_DIS3 0
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MAX4 1000
param set-default SIM_GZ_EC_DIS4 0
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_MIN5 0
param set-default SIM_GZ_EC_MAX5 1000
param set-default SIM_GZ_EC_DIS5 0
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_MIN6 0
param set-default SIM_GZ_EC_MAX6 1000
param set-default SIM_GZ_EC_DIS6 0
